// <auto-generated />
using BookManageMentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManageMentSystem.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManageMentSystem.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            Name = "The Great Gatsby",
                            Price = 15.99m
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Harper Lee",
                            Name = "To Kill a Mockingbird",
                            Price = 18.5m
                        },
                        new
                        {
                            BookId = 3,
                            Author = "George Orwell",
                            Name = "1984",
                            Price = 14.99m
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Jane Austen",
                            Name = "Pride and Prejudice",
                            Price = 12.99m
                        },
                        new
                        {
                            BookId = 5,
                            Author = "J.D. Salinger",
                            Name = "The Catcher in the Rye",
                            Price = 16.75m
                        },
                        new
                        {
                            BookId = 6,
                            Author = "J.K. Rowling",
                            Name = "Harry Potter and the Sorcerer's Stone",
                            Price = 22.99m
                        },
                        new
                        {
                            BookId = 7,
                            Author = "J.R.R. Tolkien",
                            Name = "The Hobbit",
                            Price = 19.99m
                        },
                        new
                        {
                            BookId = 8,
                            Author = "J.R.R. Tolkien",
                            Name = "The Lord of the Rings",
                            Price = 35.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
